### ISSUE TITLE
Help Needed with Missing `ck.pth` File in APISR Project

### ISSUE THREAD

**Issue by zzhanghub** [Kiteretsu77/APISR#2]
Hi APISR Team,

I've been diving into APISR and it's awesome.

Here's a little snag I've hit, though. While running `dataset_curation_pipeline/collect.py`, I bumped into this snag:

``` shell
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/ck.pth
```
I don't seem to have found this CKPT in the repo. Can you provide it?

The code seems to be looking for it right here:
``` python
class video_scoring:
    def __init__(self) -> None:

        # Init the model
        self.scorer = ICNet()
        self.scorer.load_state_dict(torch.load('pretrained/ck.pth',map_location=torch.device('cpu')))
        self.scorer.eval().cuda()
```

Thanks a ton for the help! Can't wait to get back to exploring APISR.

Cheers!

**Comment by Kiteretsu77** [comment]
Thank you for your feedback! I have added a way to download pretrained IC9600 in Readme.md (for the newest push). 
For the scripts/prepare_datasets.sh, I have also modified the scripts and pushed them to the newest commit. This new script should be capable of automatically handling cropping and hand-drawn line enhancement. Thanks!
