### ISSUE TITLE
API Dataset release

### ISSUE THREAD

**Issue by huangyang-666** [Kiteretsu77/APISR#3]
Hello, I've had the pleasure of reading your work, and I must say, I found it deeply inspiring. Your efforts are truly commendable! 
Would you kindly consider releasing the API Dataset sooner in the future? I'm eagerly looking forward to it. 
Thank you very much!

**Comment by Kiteretsu77** [comment]
Thank you so much for your attention! 
I am considering API dataset release but I think that I may release it a little bit later (late summer) because I am still using it on other projects. When I release it, I think that my format will be quite like AnimeSR and VQDSR. 
Thanks!

**Comment by Kiteretsu77** [comment]
Meanwhile, we release the dataset curation pipeline. If you want to collect your own dataset, you can follow the instructions in README. It will be very helpful!

**Comment by huangyang-666** [comment]
Thank you for your prompt response! This is truly a nice work!
