### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by Alkatras777** [Kiteretsu77/APISR#7]
I tried to install, but this is the response cmd gave me
![image](https://github.com/Kiteretsu77/APISR/assets/69349677/d0345ae4-4d22-4ae5-a80c-4e36f53dd076)

**Comment by Kiteretsu77** [comment]
I have tested on new devices and was still accessible to the git repo. I think that this is probably related to the github credential reasons. Thanks!

**Comment by xenova** [comment]
Running
```
git clone https://github.com/Kiteretsu77/APISR.git
```
should work.
