### ISSUE TITLE
4x quality not good

### ISSUE THREAD

**Issue by BillionShields** [Kiteretsu77/APISR#8]
This Upscaler does changes OG image for the worse
4x on the right. lips, eyes and flower details got worse 
![GJZLOLjWEAA2SsU](https://github.com/Kiteretsu77/APISR/assets/4848738/c9b1bda1-8b31-49b5-9058-9650daf507bd)

**Comment by Kiteretsu77** [comment]
The dataset I trained with is anime video dataset (e.g., Japanese anime) and it's not on AIGC content. I recommend you to have a look on our paper for more details. In the future, I may introduce new AIGC datasets. Thanks!
